const get = (req,res) =>{
res.send(
    [ {     "id": 1,
    "title" : " Kartik aryan on ‘Bhool Bhulaiyaa 2’ crossing the 200 crore mark; Didn’t know it will ‘revive’ Bollywood",
    "category"  : "Bollywood",
    "date" : "June 8 2022",
    "Image"    : "https://akm-img-a-in.tosshub.com/businesstoday/images/story/202205/bb2_live_updates_main_200x768_0-sixteen_nine.jpeg?size=948:533",
    "description"   : "Kartik Aaryan is currently basking in the success of Bhool Bhulaiyya. The film became a commercial success and has broken all box office records surpassing the 200 crore mark. Reflecting on the same, Kartik admitted that he ‘never imagined or thought’ that the film will cross the 200 crore mark."
},
{    "id": 2,
    "title" : " The Kashmir Files director Vivek Agnihotri and producer Pallavi Joshi celebrate their 25th wedding anniversary",
    "category"  : "Bollywood",
    "date" : "June 20 2022",
    "Image"    : "https://www.firstpost.com/wp-content/uploads/2022/06/640-x-363-2022-06-28T63658.854.jpg?impolicy=website&width=640&height=362",
    "description"   : "The Hindi remake of Tamil blockbuster movie ‘Kaithi’ starring Ajay Devgn has gone on floors with the title ‘Bholaa’",
},
{    "id": 3,
    "title" : " Aditya Roy Kapur on playing action hero in Rashtra Kavach Om: 'It’s a physically gruelling film'",
    "category"  : "Bollywood",
    "date" : "June 22  2022",
    "Image"    : "https://www.firstpost.com/wp-content/uploads/2022/06/Collage-Maker-29-Jun-2022-2.08-PM-min.jpg?impolicy=website&width=640&height=362",
    "description"   : "In Kapil Verma's Rashtra Kavach Om, Aditya Roy Kapur portrays the character of a commando. The film also stars Jackie Shroff, Sanjana Sanghi, Ashutosh Rana and Prakash Raj.",
    
},
{ "id": 4,
    "title" : " Taapsee Pannu talks about working with Shah Rukh Khan in their upcoming film Dunki",
    "category"  : "Bollywood",
    "date" : "June 24 2022",
    "Image"    : "https://www.firstpost.com/wp-content/uploads/2022/06/640-x-363-2022-06-28T94050.234.jpg?impolicy=website&width=640&height=362",
    "description"   : "Actress Taapsee Pannu says teaming up with SRK in 'Dunki' is a golden opportunity.",
    
},
{ "id": 5,
    "title" : " Samrat Prithviraj: Akshay Kumar’s historical action-drama gets OTT release date",
    "category"  : "Bollywood",
    "date" : "June 26 2022",
    "Image"    : "https://www.firstpost.com/wp-content/uploads/2022/06/Collage-Maker-28-Jun-2022-02.4-PM-min.jpg?impolicy=website&width=640&height=362",
    "description"   : "Akshay Kumar's Samrat Prithviraj presents an inspiring and entertaining saga of one of the greatest kings and fearless warriors in Indian history — Prithviraj Chauhan of the Chahamana dynasty.",
    
},
{ "id": 6,
    "title" : " A New Breakthrough Could Make It Possible To Harvest Solar Power at Night",
    "category"  : "Technology",
    "date" : "June 9 2022",
    "Image"    : "https://scitechdaily.com/images/Next-Generation-Solar-Panels-Illustration.jpg?ezimgfmt=ng%3Awebp%2Fngcb%2Frs%3Adevice%2Frscb-",
    "description"   : "Researchers have created a device that is capable of turning infrared heat into electricity through the use of a power-generation device called a ‘thermo-radiative diode’.",
    
},

{ "id": 7,
    "title" : " Research Shows That Robotic Surgery Is Safer and Improves Patient Recovery Time by 20%",
    "category"  : "Technology",
    "date" : "June 3 2022",
    "Image"    : "https://scitechdaily.com/images/Robotic-Surgery-777x583.jpg?ezimgfmt=ng:webp/ngcb",
    "description"   : "Research from the University College London and the University of Sheffield has shown that robot-assisted surgery for bladder cancer removal and repair allows patients to recover much faster and spend considerably less time in the hospital.",
    
},
{ "id": 8,
    "title" : " Samsung introduces 200MP camera sensor with smallest pixels",
    "category"  : "Technology",
    "date" : "June 23 2022",
    "Image"    : "https://www.dailypioneer.com/uploads/2022/story/images/big/samsung-introduces-200mp-camera-sensor-with-smallest-pixels-2022-06-23.jpg",
    "description"   : "Samsung on Thursday launched next-gen 200MP image sensor with the industrys smallest 0.56-micrometer pixels that will allow smartphone users to take movie-like cinematic footage.",
    
},
{ "id": 9,
    "title" : " AI adoption to add $500 bn to India's GDP by 2025: Nasscom",
    "category"  : "Technology",
    "date" : "June 24 2022",
    "Image"    : "https://www.dailypioneer.com/uploads/2022/story/images/big/ai-adoption-to-add--500-bn-to-india-s-gdp-by-2025--nasscom-2022-06-23.jpg",
    "description"   : "The adoption of artificial intelligence (AI) and data utilisation strategy can add $500 billion to India's GDP by 2025, a new Nasscom report showed on Thursday.",
    
},
{ "id": 10,
    "title" : " FERRARI SF90 Stradale beats the production lap record at this circuit",
    "category"  : "Cars",
    "date" : "June 24 2022",
    "Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/06/Ferrari-SF90-Stradale-Anglesey-lap-record.jpg?w=280&ssl=",
    "description"   : "The Ferrari SF90 Stradale has added another feather to its cap. The 000 hp plug-in hybrid supercar just lapped the Anglesey Circuit in record time.",
    
},
{ "id": 11,
    "title" : " McLaren P Spider by Lanzante debuts at Goodwood",
    "category"  : "Cars",
    "date" : "June 23 2022",
    "Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/06/lanzante-p-spider-launch-05.jpg?w=280&ssl=",
    "description"   : "Lanzante has stunned everyone on the very first day of the 2022 Goodwood Festival of Speed by showcasing a McLaren P Spider.The McLaren P Spider was commissioned by a customer, and who better to build one than the experts at Lanzante.",
},
{ "id": 12,
    "title" : " Maserati MC20 Cielo: The Italian beauty drops its top",
    "category"  : "Cars",
    "date" : "June 2 2022",
    "Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/05/maserati-mc20-cielo-0.jpg?w=280&ssl=",
    "description"   : "Maserati has taken the wraps off the convertible version of the MC20 supercar. It’s called the MC20 Cielo, and we love it!The MC20 is a gorgeous little coupe, and the Cielo takes it a step further. The car has a retractable hardtop that folds away in just 2 seconds.",
},
{ "id": 13,
    "title" : " Koenigsegg Jesko Komet looks like a burning fireball",
    "category"  : "Cars",
    "date" : "June 8 2022",
    "Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/05/Koenigsegg-Jesko-Komet-Absolut-rendering-2.jpg?w=280&ssl=",
    "description"   : "As the name suggests, the inspiration for this spec was the fireball seen when a comet / asteroid enters the Earth’s atmosphere. The front of the car is painted in Pearl White that fades into Sweet Mandarin at the rear – kind of like the long fiery tail of the space rock.",

},
{ "id": 14,
    "title" : " Lamborghini Aventador Ultimae sells for $.3 million",
    "category"  : "Cars",
    "date" : "June  22 2022",
    "Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/05/Used-2022-LAMBORGHINI-AVENTADOR-ULTIMAE-.jpg?w=280&ssl=",
    "description"   : "The Aventador Ultimae is Lamborghini’s last flagship supercar powered by a naturally aspirated V2 engine. That itself makes it quite special. With production limited to just 350 units, these cars are already selling for big bucks. Here’s one offered at a premium of €250,000.",
    
},
{ "id": 15,
    "title" : "Is running linked to ageing, increased cardiovascular risk in men?",
    "category"  : "Fitness",
    "date" : "June 27 2022",
    "Image"    : "https://images.indianexpress.com/2022/06/running_200_pexels.jpg",
    "description"   : "In the recent years, with many people becoming fitness conscious, marathon running or long-distance running has become common. According to data, the number of women participants have also reported a surge",
    
},
{ "id": 16,
    "title" : "International Day of Yoga 2022: Can yoga be a good substitute for cardio exercises?",
    "category"  : "Fitness",
    "date" : "June 26 2022",
    "Image"    : "https://images.indianexpress.com/2022/06/yoga-200.jpg",
    "description"   : "Yoga is known to impart several mental, physical and spiritual benefits. It calms the mind, alleviates stress and keeps your overall well-being in check. But, can it also give you benefits like a blood-pumping and heart-shaking cardio workout does?",
    
},
{ "id": 17,
    "title" : " Kamal Haasan does 26 clean incline pushups; sets massive fitness goals",
    "category"  : "Fitness",
    "date" : "June 24 2022",
    "Image"    : "https://images.indianexpress.com/2022/06/kamal-hassan_insta-lokesh-kanagaraj-twitter.jpg",
    "description"   : "Kamal Haasan maybe 67 years old, but he never fails to set goals — from acting to fashion and even fitness. As such, the actor’s fitness prowess ",
    
},
{ "id": 18,
    "title" : " Fitness alert: Simple exercises to strengthen and tone the core",
    "category"  : "Fitness",
    "date" : "June 20 2022",
    "Image"    : "https://images.indianexpress.com/2022/03/belly-fat_200_getty.jpg",
    "description"   : "Regularly doing core exercises not only helps build strength and stability, but also reduce belly fat, which is one of the most common issues experienced by many.",
    
},
{ "id": 19,
    "title" : " Body Absorbs Plant-Based Meat Less Than Animal-Based Meat: Study",
    "category"  : "Food",
    "date" : "June 2 2022",
    "Image"    : "https://images.news8.com/ibnlive/uploads/2022/06/plant-based-meat-656448463x2.jpg?impolicy=website&width=50&height=356",
    "description"   : "A study has suggested that protein from the plant-based meat alternatives may not be as accessible to human cells as those from real meat",
    
},
{ "id": 20,
    "title" : " Pncrease Your Brain Functioning by Incorporating These Nutritious Foods into Your Meal",
    "category"  : "Food",
    "date" : "June 23 2022",
    "Image"    : "https://images.news8.com/ibnlive/uploads/2022/06/untitled-design-24-654678803x2.png?impolicy=website&width=50&height=356",
    "description"   : "It is extremely crucial to include certain foods in our daily meal, which plays an important role in our cognitive functioning",
    
},
{ "id": 21,
    "title" : " “Hill Station Main Corn, Pakodas Or Momos?” Tahira Kashyap Wants To Know Your Pick",
    "category"  : "Food",
    "date" : "June 22 2022",
    "Image"    : "https://c.ndtvimg.com/2022-06/frt4j6qo_bhutta_625x300_29_June_22.jpg",
    "description"   : "Tahira Kashyap is back with her food stories. And this time, with glimpses of her indulgences from a hill station. She is a hardcore foodie who likes to share her gastronomic adventures with followers on social media",
    
},
{ "id": 22,
    "title" : " Keep Yourself Hydrated and Fresh With This Tasty Tangy Kokum Drink",
    "category"  : "Food",
    "date" : "June 24 2022",
    "Image"    : "https://images.news8.com/ibnlive/uploads/2022/06/summer-drinks-655903323x2.jpg?impolicy=website&width=50&height=356",
    "description"   : "Keeping yourself hydrated is of primary importance and an easy way to tackle major problems",
    
},
{ "id": 23,
    "title" : " Un-Layering the Delicious South Indian Malabar Parotta",
    "category"  : "Food",
    "date" : "June 27 2022",
    "Image"    : "https://images.news8.com/ibnlive/uploads/2022/06/malabar-paratha-656669553x2.jpg?impolicy=website&width=50&height=356",
    "description"   : "One dish that slips right out from this stereotypical image but is equally popular, so much so that it can be considered as one of the signature dishes in South India, is the Malabar Parotta",
    
}]
)    
} 
module.exports.ApiController = get