const get = (req,res) =>{
res.send(
   [ {     "id": 1,
"title" : " Laal Singh Chaddha: Was this Akshay Kumar co-star the first choice for Kareena Kapoor Khan's role in Aamir Khan starrer?",
"category"  : "Bollywood",
"date" : "June 8 2022",
"Image"    : "https://st1.bollywoodlife.com/wp-content/uploads/2022/08/Aamir-Kareena-Manushi-.jpg?impolicy=Medium_Widthonly&w=800",
"description"   : "Laal Singh Chaddha stars Aamir Khan and Kareena Kapoor Khan are seen in the recently released episode of Karan Johar’s chat show Koffee With Karan 7. As expected many revelations were made by them and one of them is about Kareena not being the first choice for Laal Singh Chaddha. Earlier, in an interview, Aamir had revealed that they were looking for an actress who was in a certain age group and Kareena was not on their mind. But, when they saw a video sent by the casting director, he and filmmaker Advait Chandan agreed that Kareena can be their Rupa."
},
{    "id": 2,
"title" : " The Kashmir Files director Vivek Agnihotri and producer Pallavi Joshi celebrate their 25th wedding anniversary",
"category"  : "Bollywood",
"date" : "June 20 2022",
"Image"    : "https://ichef.bbci.co.uk/news/976/cpsprodpb/62BD/production/_123677252_kfposter.jpg",
"description"   : "The Hindi remake of Tamil blockbuster movie ‘Kaithi’ starring Ajay Devgn has gone on floors with the title ‘Bholaa’",
},
{    "id": 3,
"title" : " Pathaan star Shah Rukh Khan finally STOPS hiding his face from paparazzi; fans say, 'King is back'",
"category"  : "Bollywood",
"date" : "June 22  2022",
"Image"    : "https://st1.bollywoodlife.com/wp-content/uploads/2022/08/Shah-Rukh-Khan-shows-face-.jpg",
"description"   : "If you are Shah Rukh Khan fan, and following everything about him, you would know that from the past few months, the superstar was avoiding getting clicked by paparazzi. He used to try to hide his face by using an umbrella, mask, or hoodie. However, today something different happened when he was clicked at the airport.",

},
{ "id": 4,
"title" : " Taapsee Pannu talks about working with Shah Rukh Khan in their upcoming film Dunki",
"category"  : "Bollywood",
"date" : "June 24 2022",
"Image"    : "https://c.ndtvimg.com/2022-07/073e6hog_srk_120x90_28_July_22.jpg",
"description"   : "Actress Taapsee Pannu says teaming up with SRK in 'Dunki' is a golden opportunity.",

},
{ "id": 5,
"title" : " Samrat Prithviraj: Akshay Kumar’s historical action-drama gets OTT release date",
"category"  : "Bollywood",
"date" : "June 26 2022",
"Image"    : "https://resize.indiatv.in/resize/newbucket/1200_675/2022/06/samrat-prithviraj-1654155964.jpg",
"description"   : "Akshay Kumar's Samrat Prithviraj presents an inspiring and entertaining saga of one of the greatest kings and fearless warriors in Indian history — Prithviraj Chauhan of the Chahamana dynasty.",

},
{ "id": 6,
"title" : " A New Breakthrough Could Make It Possible To Harvest Solar Power at Night",
"category"  : "Technology",
"date" : "June 9 2022",
"Image"    : "https://scitechdaily.com/images/Next-Generation-Solar-Panels-Illustration.jpg?ezimgfmt=ng%3Awebp%2Fngcb%2Frs%3Adevice%2Frscb-",
"description"   : "Researchers have created a device that is capable of turning infrared heat into electricity through the use of a power-generation device called a ‘thermo-radiative diode’.",

},

{ "id": 7,
"title" : " Research Shows That Robotic Surgery Is Safer and Improves Patient Recovery Time by 20%",
"category"  : "Technology",
"date" : "June 3 2022",
"Image"    : "https://scitechdaily.com/images/Robotic-Surgery-777x583.jpg?ezimgfmt=ng:webp/ngcb",
"description"   : "Research from the University College London and the University of Sheffield has shown that robot-assisted surgery for bladder cancer removal and repair allows patients to recover much faster and spend considerably less time in the hospital.",

},
{ "id": 8,
"title" : " Samsung introduces 200MP camera sensor with smallest pixels",
"category"  : "Technology",
"date" : "June 23 2022",
"Image"    : "https://www.dailypioneer.com/uploads/2022/story/images/big/samsung-introduces-200mp-camera-sensor-with-smallest-pixels-2022-06-23.jpg",
"description"   : "Samsung on Thursday launched next-gen 200MP image sensor with the industrys smallest 0.56-micrometer pixels that will allow smartphone users to take movie-like cinematic footage.",

},
{ "id": 9,
"title" : " AI adoption to add $500 bn to India's GDP by 2025: Nasscom",
"category"  : "Technology",
"date" : "June 24 2022",
"Image"    : "https://www.dailypioneer.com/uploads/2022/story/images/big/ai-adoption-to-add--500-bn-to-india-s-gdp-by-2025--nasscom-2022-06-23.jpg",
"description"   : "The adoption of artificial intelligence (AI) and data utilisation strategy can add $500 billion to India's GDP by 2025, a new Nasscom report showed on Thursday.",

},
{ "id": 10,
"title" : " FERRARI SF90 Stradale beats the production lap record at this circuit",
"category"  : "Cars",
"date" : "June 24 2022",
"Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/06/Ferrari-SF90-Stradale-Anglesey-lap-record.jpg?w=280&ssl=",
"description"   : "The Ferrari SF90 Stradale has added another feather to its cap. The 000 hp plug-in hybrid supercar just lapped the Anglesey Circuit in record time.",

},
{ "id": 11,
"title" : " McLaren P Spider by Lanzante debuts at Goodwood",
"category"  : "Cars",
"date" : "June 23 2022",
"Image"    : "https://cdn.carbuzz.com/gallery-images/840x560/1011000/200/1011202.jpg",
"description"   : "Lanzante has stunned everyone on the very first day of the 2022 Goodwood Festival of Speed by showcasing a McLaren P Spider.The McLaren P Spider was commissioned by a customer, and who better to build one than the experts at Lanzante.",
},
{ "id": 12,
"title" : " Maserati MC20 Cielo: The Italian beauty drops its top",
"category"  : "Cars",
"date" : "June 2 2022",
"Image"    : "https://i.ytimg.com/vi/feQtFZzLPKo/maxresdefault.jpg",
"description"   : "Maserati has taken the wraps off the convertible version of the MC20 supercar. It’s called the MC20 Cielo, and we love it!The MC20 is a gorgeous little coupe, and the Cielo takes it a step further. The car has a retractable hardtop that folds away in just 2 seconds.",
},
{ "id": 13,
"title" : " Koenigsegg Jesko Komet looks like a burning fireball",
"category"  : "Cars",
"date" : "June 8 2022",
"Image"    : "https://i0.wp.com/www.thesupercarblog.com/wp-content/uploads/2022/05/Koenigsegg-Jesko-Komet-Absolut-rendering-2.jpg?w=280&ssl=",
"description"   : "As the name suggests, the inspiration for this spec was the fireball seen when a comet / asteroid enters the Earth’s atmosphere. The front of the car is painted in Pearl White that fades into Sweet Mandarin at the rear – kind of like the long fiery tail of the space rock.",

},
{ "id": 14,
"title" : " Lamborghini Aventador Ultimae sells for $.3 million",
"category"  : "Cars",
"date" : "June  22 2022",
"Image"    : "https://www.autocar.co.uk/sites/autocar.co.uk/files/images/car-reviews/first-drives/legacy/1-lamborghini-aventador-ultimae-2022-first-drive-lead.jpg",
"description"   : "The Aventador Ultimae is Lamborghini’s last flagship supercar powered by a naturally aspirated V2 engine. That itself makes it quite special. With production limited to just 350 units, these cars are already selling for big bucks. Here’s one offered at a premium of €250,000.",

},
{ "id": 15,
"title" : "Is running linked to ageing, increased cardiovascular risk in men?",
"category"  : "Fitness",
"date" : "June 27 2022",
"Image"    : "https://images.indianexpress.com/2022/06/running_200_pexels.jpg",
"description"   : "In the recent years, with many people becoming fitness conscious, marathon running or long-distance running has become common. According to data, the number of women participants have also reported a surge",

},
{ "id": 16,
"title" : "International Day of Yoga 2022: Can yoga be a good substitute for cardio exercises?",
"category"  : "Fitness",
"date" : "June 26 2022",
"Image"    : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVe3eoHWAk9zDJC9092P2wvJNsj6_s1r-2UQ&usqp=CAU",
"description"   : "Yoga is known to impart several mental, physical and spiritual benefits. It calms the mind, alleviates stress and keeps your overall well-being in check. But, can it also give you benefits like a blood-pumping and heart-shaking cardio workout does?",

},
{ "id": 17,
"title" : " Kamal Haasan does 26 clean incline pushups; sets massive fitness goals",
"category"  : "Fitness",
"date" : "June 24 2022",
"Image"    : "https://images.indianexpress.com/2022/06/kamal-hassan_insta-lokesh-kanagaraj-twitter.jpg",
"description"   : "Kamal Haasan maybe 67 years old, but he never fails to set goals — from acting to fashion and even fitness. As such, the actor’s fitness prowess ",

},
{ "id": 18,
"title" : " Fitness alert: Simple exercises to strengthen and tone the core",
"category"  : "Fitness",
"date" : "June 20 2022",
"Image"    : "https://cdn.slidesharecdn.com/ss_thumbnails/15minutefitness8quickandeasyexercisesstrengthenandtoneimprovecorefitnessfatburningaerobicworkouts-210921224823-thumbnail-4.jpg?cb=1632264840",
"description"   : "Regularly doing core exercises not only helps build strength and stability, but also reduce belly fat, which is one of the most common issues experienced by many.",

},
{ "id": 19,
"title" : " Body Absorbs Plant-Based Meat Less Than Animal-Based Meat: Study",
"category"  : "Food",
"date" : "June 2 2022",
"Image"    : "https://images.news18.com/ibnlive/uploads/2022/06/plant-based-meat-16564148463x2.jpg",
"description"   : "A study has suggested that protein from the plant-based meat alternatives may not be as accessible to human cells as those from real meat",

},
{ "id": 20,
"title" : " Increase Your Brain Functioning by Incorporating These Nutritious Foods into Your Meal",
"category"  : "Food",
"date" : "June 23 2022",
"Image"    : "https://www.eatright.org/-/media/eatrightimages/health/wellness/healthyaging/4typesoffoodstohelpboostyourmemory.jpg?h=450&w=600&la=en&hash=1721F4341F5F9FFED18A32C306CEC6F356D0ECFF",
"description"   : "It is extremely crucial to include certain foods in our daily meal, which plays an important role in our cognitive functioning",

},
{ "id": 21,
"title" : " “Hill Station Main Corn, Pakodas Or Momos?” Tahira Kashyap Wants To Know Your Pick",
"category"  : "Food",
"date" : "June 22 2022",
"Image"    : "https://c.ndtvimg.com/2022-06/frt4j6qo_bhutta_625x300_29_June_22.jpg",
"description"   : "Tahira Kashyap is back with her food stories. And this time, with glimpses of her indulgences from a hill station. She is a hardcore foodie who likes to share her gastronomic adventures with followers on social media",

},
{ "id": 22,
"title" : " Keep Yourself Hydrated and Fresh With This Tasty Tangy Kokum Drink",
"category"  : "Food",
"date" : "June 24 2022",
"Image"    : "https://images.indianexpress.com/2020/05/kokum1.jpg?w=389",
"description"   : "Keeping yourself hydrated is of primary importance and an easy way to tackle major problems",

},
{ "id": 23,
"title" : " Un-Layering the Delicious South Indian Malabar Parotta",
"category"  : "Food",
"date" : "June 27 2022",
"Image"    : "https://images.news18.com/ibnlive/uploads/2022/06/malabar-paratha-16561669524x3.jpg",
"description"   : "One dish that slips right out from this stereotypical image but is equally popular, so much so that it can be considered as one of the signature dishes in South India, is the Malabar Parotta",

}]
)    
} 
module.exports.ApiController = get
